from wxPython.wx import *
from wxshtoomframe import ShtoomMainFrame
from shtoom.ui.base import ShtoomBaseUI

# Implements the ShtoomMainFrame class as generated by
# wxglade. Call me paranoid but I'm not sticking this code
# in a generated file - no matter how bug free and fantastic
# the code is.

class ShtoomMainFrameImpl(ShtoomMainFrame, ShtoomBaseUI):
    MENU_PREFS = 101
    MENU_EXIT = 102
    MENU_HELP_CONTENTS = 103

    def __init__(self, *args, **kwds):
        ShtoomMainFrame.__init__(self, *args, **kwds)
        EVT_MENU(self, self.MENU_EXIT, self.DoExit)

    def DoExit(self, event):
        self.Close(True)
        reactor.stop()
