#!/usr/bin/env python
# originally generated by wxGlade 0.3.1 on Mon Apr 19 22:10:30 2004

from wxPython.wx import *

class PreferencesDialog(wxDialog):
    BUTT_PREFS_SAVE = 100
    BUTT_PREFS_CANCEL = 101

    def __init__(self, *args, **kwds):
        self.main = kwds['main']
        self.opts = kwds['opts']

        # begin wxGlade: PreferencesDialog.__init__
        kwds["style"] = wxDEFAULT_DIALOG_STYLE
        wxDialog.__init__(self, None, -1, "Edit Preferences")
        self.prefs_notebook = wxNotebook(self, -1, style=0)
        self.prefs_save = wxButton(self, wxID_OK, "Save", style=wxBU_EXACTFIT)
        self.prefs_cancel = wxButton(self, wxID_CANCEL, "Cancel", 
            style=wxBU_EXACTFIT)
        self.__set_properties()
        # end wxGlade

        self.options = {}
        self.tabs = {}

        for group in self.opts:
            nbpage = wxPanel(self.prefs_notebook, -1)
            nbsizer = wxBoxSizer(wxVERTICAL)
            nbpage.SetSizer(nbsizer)

            groupname = group.getName()
            for optnumber, option in enumerate(group):
                optname = option.getName()
                optsizer = wxBoxSizer(wxHORIZONTAL)
                nbsizer.Add(optsizer)

                optlabel = wxStaticText(nbpage, -1, option.getPrettyName())
                optsizer.Add(optlabel, 0, wxALL|wxALIGN_CENTER, 5)
                if option.optionType in ( 'String', 'Number', 'Password' ):
                    style = 0
                    if option.optionType == 'Password':
                        flags &= wxTE_PASSWORD
                    editwidget = wxTextCtrl(nbpage, -1, style=style)
                elif option.optionType == 'Boolean':
                    editwidget = wxCheckBox(nbpage, -1, "")
                elif option.optionType == 'Choice':
                    choices = option.getChoices()
                    rbs = [c for c in option.getChoices()]
                    editwidget = wxRadioBox(nbpage, -1, "", choices=rbs, 
                        majorDimension=1, style=wxRA_SPECIFY_ROWS)
                else:
                    print >>sys.stderr, "unknown option type"
                    continue
                optsizer.Add(editwidget, 1, wxALL|wxALIGN_CENTER, 5)
                self.options[optname] = (option.optionType, None, None)
            self.tabs[groupname] = None
            self.prefs_notebook.AddPage(nbpage, groupname)

        self.__do_layout()
            
    def __set_properties(self):
        # begin wxGlade: PreferencesDialog.__set_properties
        self.SetTitle("Edit Preferences")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PreferencesDialog.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_2 = wxBoxSizer(wxHORIZONTAL)
        sizer_1.Add(wxNotebookSizer(self.prefs_notebook), 1, wxEXPAND, 0)
        sizer_2.Add(self.prefs_save, 1, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 5)
        sizer_2.Add(self.prefs_cancel, 1, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 5)
        sizer_1.Add(sizer_2, 0, wxEXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class PreferencesDialog


