#!/usr/bin/env python
# generated by wxGlade 0.3.2 on Sun Mar 28 21:41:24 2004

import wx

class ShtoomMainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ShtoomMainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.advanced = wx.Panel(self, -1)
        
        # Menu Bar
        self.shtoom_frame_menubar = wx.MenuBar()
        self.SetMenuBar(self.shtoom_frame_menubar)
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(self.MENU_PREFS, "Preferences", "Edit Shtoom preferences", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(self.MENU_EXIT, "Exit", "Exit Shtoom", wx.ITEM_NORMAL)
        self.shtoom_frame_menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(self.MENU_HELP_CONTENTS, "Contents", "Give me some help", wx.ITEM_NORMAL)
        self.shtoom_frame_menubar.Append(wxglade_tmp_menu, "Help")
        # Menu Bar end
        self.shtoom_frame_statusbar = self.CreateStatusBar(1, 0)
        self.label_1 = wx.StaticText(self, -1, "Address:", style=wx.ALIGN_CENTRE)
        self.combo_address = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN)
        self.button_call = wx.Button(self, self.BUTT_CALL, "Call")
        self.button_hangup = wx.Button(self, self.BUTT_HANGUP, "Hang Up")
        self.button_register = wx.Button(self, self.BUTT_REGISTER, "Register")
        self.button_advanced = wx.Button(self, self.BUTT_ADVANCED, "-")
        self.button_1 = wx.Button(self.advanced, -1, "1", style=1)
        self.button_2 = wx.Button(self.advanced, -1, "2", style=1)
        self.button_3 = wx.Button(self.advanced, -1, "3", style=1)
        self.button_4 = wx.Button(self.advanced, -1, "4", style=1)
        self.button_5 = wx.Button(self.advanced, -1, "5", style=1)
        self.button_6 = wx.Button(self.advanced, -1, "6", style=1)
        self.button_7 = wx.Button(self.advanced, -1, "7", style=1)
        self.button_8 = wx.Button(self.advanced, -1, "8", style=1)
        self.button_9 = wx.Button(self.advanced, -1, "9", style=1)
        self.button_star = wx.Button(self.advanced, -1, "*", style=1)
        self.button_0 = wx.Button(self.advanced, -1, "0", style=1)
        self.button_hash = wx.Button(self.advanced, -1, "#", style=1)
        self.text_messages = wx.TextCtrl(self.advanced, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ShtoomMainFrame.__set_properties
        self.SetTitle("Shtoom")
        self.shtoom_frame_statusbar.SetStatusWidths([-1])
        # statusbar fields
        shtoom_frame_statusbar_fields = ["shtoom_frame_statusbar"]
        for i in range(len(shtoom_frame_statusbar_fields)):
            self.shtoom_frame_statusbar.SetStatusText(shtoom_frame_statusbar_fields[i], i)
        self.combo_address.SetSelection(0)
        self.button_advanced.SetSize((20, 27))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ShtoomMainFrame.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.GridSizer(4, 3, 0, 0)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.label_1, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_3.Add(self.combo_address, 1, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        sizer_4.Add(self.button_call, 1, wx.ALL, 5)
        sizer_4.Add(self.button_hangup, 1, wx.ALL, 5)
        sizer_4.Add(self.button_register, 1, wx.ALL, 5)
        sizer_4.Add(self.button_advanced, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_2.Add(sizer_4, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.button_1, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.button_2, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.button_3, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.button_4, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.button_5, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.button_6, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.button_7, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.button_8, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.button_9, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.button_star, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.button_0, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_1.Add(self.button_hash, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_1.Add(grid_sizer_1, 0, wx.EXPAND, 0)
        sizer_1.Add(self.text_messages, 1, wx.ALL|wx.EXPAND, 3)
        self.advanced.SetAutoLayout(1)
        self.advanced.SetSizer(sizer_1)
        sizer_1.Fit(self.advanced)
        sizer_1.SetSizeHints(self.advanced)
        sizer_2.Add(self.advanced, 1, wx.EXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        #sizer_2.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class ShtoomMainFrame


